// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {network} from '../models';
import {fsnotify} from '../models';

export function AddFile():Promise<string>;

export function DiscoverDevices():Promise<Array<network.Device>>;

export function FileWatcher(arg1:string):Promise<void>;

export function GetLocalIP():Promise<string>;

export function HandleFileEvent(arg1:fsnotify.Event):Promise<void>;

export function PingDevice(arg1:string):Promise<network.PingResponse>;

export function SendFile(arg1:string,arg2:string):Promise<void>;
