// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {network} from '../models';

export function AddFile():Promise<string>;

export function DiscoverDevices():Promise<Array<string>>;

export function GetLocalIP():Promise<string>;

export function PingDevice(arg1:string):Promise<network.PingResponse>;
