// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFile() {
  return window['go']['main']['App']['AddFile']();
}

export function DiscoverDevices() {
  return window['go']['main']['App']['DiscoverDevices']();
}

export function FileWatcher(arg1) {
  return window['go']['main']['App']['FileWatcher'](arg1);
}

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function HandleFileEvent(arg1) {
  return window['go']['main']['App']['HandleFileEvent'](arg1);
}

export function PingDevice(arg1) {
  return window['go']['main']['App']['PingDevice'](arg1);
}
